### ISSUE TITLE
Reduce Installer Size

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#1090]
Some options to explore for doing this (in order of priority):
- [x] Launch Lantern in system-default browser (#1151)
- [ ] Support Firefox in addition to Chrome (#1112)
- [x] Replace the embedded GeoLite City database with GeoLite Country for purposes of identifying general region (#1106)
- [x] Use ProGuard to reduce code size (see #670 and #821)
