### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#1102]
Base tests that should be run for all releases. Some clearly should be run with full installers while others such as pulling in translation strings should happen before installers are built. This means running the QA script on these platforms:
- [ ] Deploy any required updates to the controller
- [ ] All tests should be passing on CI box
- [ ] translations update/audit (à la #1095)
- [ ] Test on Ubuntu 12.04 
- [ ] Test on Windows XP
- [ ] Test on Windows 7
- [ ] Test on Windows 8
- [ ] Test on OSX 10.9
- [ ] Test on OSX 10.6
- [ ] Update https://<lantern-controller-id>.appspot.com/admin/latest.html
- [ ] Announce new version on user and developer lists
- [ ] Send out new version email to all existing users as appropriate
- [ ] Invite uninvited users who have requested invites as appropriate

------- Country testing -------
- [ ] Test from our box in China
- [ ] Test from a box in Iran (and ask appropriate folks to set up a box if needed)

------- Optional -------
- [ ] Test on Ubuntu 12.10
- [ ] Test on Ubuntu 13.04
- [ ] Test on Ubuntu 13.10
- [ ] Test on Windows Vista
- [ ] Test on OSX 10.7
- [ ] Test on OSX 10.8

Additional Tasks:
Run FindBugs, either in Eclipse or maven.

Release-specific tests:
