### ISSUE TITLE
update UI specs

### ISSUE THREAD

**Issue by lanterndev** [getlantern/lantern#1396]
- [ ] friend suggestions (see e.g. https://github.com/getlantern/lantern/issues/1321#issuecomment-32669503)
- [ ] more stats, e.g. uptime (#1025)
- [x] rename "gtalk" fields (getlantern/lantern-ui#51)

anything else needed to support forthcoming improvements:
- [ ] ux
- [ ] kaleidoscope info
- [ ] persona support
- [ ] anonymized jabberids
- [ ] ???
