### ISSUE TITLE
Implement CloudFlare Trick to Safely Distribute Fallbacks (Meta Ticket)

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#1437]
- [ ] Distribute list of all unblocked CloudFlare sites in S3 configuration #1438 
- [ ] Support use of DNS names for fallbacks in addition to IPs #1439
- [x] Update invitation process to distribute CloudFlare DNS names for fallbacks instead of IPs #1440
- [ ] Add support for CloudFlare proxies on client and fallbacks #1441
