### ISSUE TITLE
Allow new invited users to find out about fallbacks even though S3 is blocked in China

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#1643]
China has started blocking S3 aggressively, which creates a problem for us because we currently distribute installer wrappers via S3.  The installer wrappers encapsulate information about a user's fallback by including the URL to the user-specific S3 configuration.

To deal with this, we will stop distributing custom installer wrappers and instead just point people at our open download which we will mirror in a variety of places to keep it available.  The open download uses Flashlight/Fastly to proxy traffic.

Once someone logs in, they will be given access to a new REST service on the controller that distributes the same information that used to be distributed through S3.  This will allow them to find out about their custom fallback, and then continue to use Lantern as before.

This requires several changes
- [x] #1644 Update invitation email to point at open downloads (should probably include all mirrors)
- [x] #1645 Stop building installer wrappers
- [x] #1646 Create REST service for getting S3Config info from controller
- [x] #1647 Update S3ConfigFetcher to use REST service for getting S3Config info from controller
