### ISSUE TITLE
better experience when landing on the visualization after initial setup

### ISSUE THREAD

**Issue by skivvies** [getlantern/lantern#967]
When the user is first shown the map visualization after initial setup, it's currently a letdown due to showing no other people on the map or other activity.

Here are a few things we can do to improve this:

- [ ] #634 - show all contacts on the map visualization
- [ ] #969 - consider showing all online lantern instances on map, not just contacts and those you've connected to
- [ ] #965 - guided tour of map visualization after initial setup
- [ ] #966 - add a buddy list and chat capability overlaid on map
- [ ] #1025 - show running count of total time running lantern
- [ ] #1024 - consider not showing visualization after initial setup
- [ ] #1026 - don't show personal activity stats only in a tooltip
- [ ] #1027 - consider tracking and displaying more statistics
- [ ] #1355 - everybody should start out as friends with the "Lantern Friend" user
- [ ] #1064 - Give mode proxy isn't showing connections from active Get mode proxy
